* git-credential-msal

This repository contains tooling to help with git over HTTP flows using
Microsoft SSO with OIDC Id tokens. For information on how to configure the
server for this flow, please look at the [[https://binary-eater.github.io/posts/git_oidc/][related blog post]].

** Dependencies

Required dependencies

+ ~msal-python~
+ ~pyjwt~
+ ~keyring~
+ ~pyxdg~

** Setup

Run the following to have ~git~ utilize the credential helper.

#+BEGIN_SRC sh
git config --global --add credential.helper msal
#+END_SRC

If you are only going to use this helper for a select few repos, you could
consider not using the ~--global~ flag.

You may want to use this helper in combination with another helper that supports
the store action.

#+BEGIN_SRC sh
git config --global --add credential.helper cache
git config --global --add credential.helper msal
#+END_SRC

To configure the Microsoft Entra Id application client id and tenant id that
~git-credential-msal~ will use for SSO, the following commands can be used.

#+BEGIN_SRC sh
git config --global credential.https://git.example.com.msalClientId <MSFT Entra Id App Client Id>
git config --global credential.https://git.example.com.msalTenantId <MSFT Entra Id App Tenant Id>
#+END_SRC

**NOTE:** the server does need to at minimum advertise ~WWW-Authenticate:
  Bearer~ in its initial 401 response for ~git-credential-msal~ to consider
  forwarding the bearer token to the server.
